"""Supplementary material — full per-run tables, hyperparameter sweeps, and code listing summary."""

import os
import pandas as pd
from docx import Document
from docx.shared import Pt, Inches, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RES = os.path.join(ROOT, "results")
OUT = os.path.join(ROOT, "paper", "Supplementary_Material.docx")

doc = Document()
style = doc.styles["Normal"]
style.font.name = "Times New Roman"; style.font.size = Pt(10.5)


def H(text, level=1):
    h = doc.add_heading(text, level=level)
    for r in h.runs:
        r.font.name = "Times New Roman"; r.font.color.rgb = RGBColor(0, 0, 0)


def P(text, italic=False, bold=False, align=None, size=10.5):
    p = doc.add_paragraph()
    if align == "center": p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    elif align == "justify": p.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY
    r = p.add_run(text); r.italic = italic; r.bold = bold
    r.font.name = "Times New Roman"; r.font.size = Pt(size)


def add_table(df, caption=None, decimals=4):
    if caption:
        cap = doc.add_paragraph(); cap.alignment = WD_ALIGN_PARAGRAPH.CENTER
        r = cap.add_run(caption); r.bold = True
        r.font.name = "Times New Roman"; r.font.size = Pt(9.5)
    tbl = doc.add_table(rows=1 + len(df), cols=len(df.columns))
    tbl.style = "Light Grid Accent 1"
    for j, col in enumerate(df.columns):
        c = tbl.rows[0].cells[j]; c.text = str(col)
        for p in c.paragraphs:
            for r in p.runs:
                r.bold = True; r.font.name = "Times New Roman"; r.font.size = Pt(9)
    for i, row in enumerate(df.itertuples(index=False), start=1):
        for j, val in enumerate(row):
            txt = f"{val:.{decimals}f}" if isinstance(val, float) else str(val)
            tbl.rows[i].cells[j].text = txt
            for p in tbl.rows[i].cells[j].paragraphs:
                for r in p.runs:
                    r.font.name = "Times New Roman"; r.font.size = Pt(9)


title = doc.add_paragraph(); title.alignment = WD_ALIGN_PARAGRAPH.CENTER
r = title.add_run("Supplementary Material — QIDDM")
r.bold = True; r.font.name = "Times New Roman"; r.font.size = Pt(14)
P("")

H("S1. Per-Run Utility Table (all methods, all instances)", level=1)
df = pd.read_csv(os.path.join(RES, "main_per_run.csv"))
sub = df[["instance", "method", "run", "utility", "cpu_time",
          "iterations_to_best"]].copy()
sub.columns = ["Instance", "Method", "Run", "Utility", "CPU (s)", "Iter→best"]
add_table(sub.head(60), "Table S1 (extract). First 60 of "
          f"{len(sub)} per-run records. Full CSV in repository.",
          decimals=4)

H("S2. Ablation Per-Run Table", level=1)
abl = pd.read_csv(os.path.join(RES, "ablation_per_run.csv"))
add_table(abl.head(50), "Table S2. Ablation per-run results (first 50).", decimals=4)

H("S3. Sensitivity Per-Run Table", level=1)
sens = pd.read_csv(os.path.join(RES, "sensitivity_per_run.csv"))
add_table(sens, "Table S3. Sensitivity per-run results.", decimals=4)

H("S4. Friedman Test Output", level=1)
try:
    fr = pd.read_csv(os.path.join(RES, "friedman_tests.csv"))
    add_table(fr, "Table S4. Friedman omnibus test across "
              "GA / PSO / QEA / QIDDM.", decimals=4)
except Exception:
    P("Friedman output not generated.")

H("S5. Hardware and Software", level=1)
P("All experiments executed on a single CPU thread (Windows 10, Python "
  "3.14.2, NumPy 2.x, SciPy 1.17, pandas 2.x, matplotlib 3.x, "
  "python-docx). The vectorised QIDDM rotation gate uses NumPy "
  "broadcasting and avoids per-q-bit Python loops, enabling N = 200 "
  "runs in ≈ 3 s each. Full environment specification (`requirements.txt`) "
  "and seeds (0–19) are released with the code.", align="justify")

H("S6. Reproducibility Checklist", level=1)
P("• All random seeds fixed and documented (0–19 for stochastic methods, "
  "and instance-specific seeds 42, 123, 2026, 314, 7).")
P("• All datasets generated by fixed-seed reproducible scripts; no "
  "stochastic external resources.")
P("• All numerical results in Tables 1–4 of the main paper "
  "regenerable by `python experiments/run_full_experiment.py`.")
P("• All figures regenerable by `python experiments/make_full_plots.py`.")
P("• Hyper-parameters listed in main paper Section 5 and `qiddm.py`.")

H("S7. Code Repository Layout", level=1)
P("qiddm_paper/")
P("├── benchmarks/")
P("│   ├── problem.py             # MC-CSSP synthetic generator")
P("│   └── realworld.py           # Real-world-correlated instance")
P("├── algorithms/")
P("│   ├── baselines.py           # TOPSIS, AHP, GA, PSO")
P("│   ├── extra_baselines.py     # Han-Kim QEA, EXACT enumeration")
P("│   ├── qiddm.py               # Proposed QIDDM (vectorised)")
P("│   └── qiddm_ablation.py      # Ablation variants")
P("├── experiments/")
P("│   ├── run_full_experiment.py # Main + ablation + sensitivity + stats")
P("│   └── make_full_plots.py     # All figures + graphical abstract")
P("├── results/                   # CSVs + PNGs + NPZ convergence")
P("└── paper/                     # docx outputs")

doc.save(OUT)
print("Saved:", OUT)
